function export_stage3_parity_case( ...
    outFile,gnb2ris,ris2ue,geometry,c0,lambda0,KBR,KRU,lspBR,lspRU)
%EXPORT_STAGE3_PARITY_CASE
% Golden case for Python Stage-3 analytical RIS statistics.
%
% This function rebuilds Stage 1 + Stage 2 in MATLAB, then uses a
% deterministic W and deterministic RIS phase pattern to export:
%
%   UBR, muFeff, sigma2Feff, muSNR, Cmat, sigma2Wick
%
% No Monte Carlo Feff is required.
%
% Example:
%
% export_stage3_parity_case( ...
%     "stage3_case.mat", ...
%     gnb2ris,ris2ue,geometry,c0,lambda_0, ...
%     K_BR,K_RU,lsp_BR,lsp_RU);

    [muBR,sigma2BR,dbarTBR,dbarRBR] = ...
        generate_channel_moments_no_cdl( ...
            gnb2ris,geometry.ris2gnb,geometry.gnb2ris, ...
            c0,lambda0,KBR,lspBR);

    [muRU,sigma2RU,dbarTRU,dbarRRU] = ...
        generate_channel_moments_no_cdl( ...
            ris2ue,geometry.ue2ris,geometry.ris2ue, ...
            c0,lambda0,KRU,lspRU);

    [rhoRB,rhoBR] = compute_ch_eff_rho_avg_fast( ...
        dbarTBR,dbarRBR,geometry.ris2gnb,geometry.gnb2ris, ...
        lspBR.mu_ASA,lspBR.sigma_ASA, ...
        lspBR.mu_ZSA,lspBR.sigma_ZSA, ...
        lspBR.mu_ASD,lspBR.sigma_ASD, ...
        lspBR.mu_ZSD,lspBR.sigma_ZSD, ...
        lspBR.c_ASA,lspBR.c_ZSA,lspBR.c_ASD,lspBR.c_ZSD, ...
        lspBR.mu_offset_ZOD,lambda0);

    rhoRUhopBase = compute_ch_rho_avg( ...
        dbarTRU,geometry.ris2ue, ...
        lspRU.mu_ASD,lspRU.sigma_ASD, ...
        lspRU.mu_ZSD,lspRU.sigma_ZSD, ...
        lspRU.c_ASD,lspRU.c_ZSD, ...
        lspRU.mu_offset_ZOD,lambda0);

    rhoRUhop = sigma2RU*rhoRUhopBase;

    [rhoRU,rhoUR] = compute_ch_eff_rho_avg_fast( ...
        dbarTRU,dbarRRU,geometry.ue2ris,geometry.ris2ue, ...
        lspRU.mu_ASA,lspRU.sigma_ASA, ...
        lspRU.mu_ZSA,lspRU.sigma_ZSA, ...
        lspRU.mu_ASD,lspRU.sigma_ASD, ...
        lspRU.mu_ZSD,lspRU.sigma_ZSD, ...
        lspRU.c_ASA,lspRU.c_ZSA,lspRU.c_ASD,lspRU.c_ZSD, ...
        lspRU.mu_offset_ZOD,lambda0);

    nRIS = size(muBR,1);
    nT = size(muBR,2);

    % Deterministic normalized complex W. Type-I membership is irrelevant
    % for numerical parity of the analytical formulas.
    idxT = (0:nT-1).';
    W = exp(1i*2*pi*idxT/max(nT,1))/sqrt(nT);

    % Deterministic binary phase pattern.
    z = mod((0:nRIS-1).',2);
    phaseLevels = deg2rad([45 135]);
    phi = phaseLevels(z+1);
    [beta,gamma] = generate_ris_response(phi);

    [muFeff,sigma2Feff,UBR] = generate_eff_moments( ...
        W,gamma, ...
        rhoRB,rhoBR, ...
        lspBR.mu_XPR,lspBR.sigma_XPR, ...
        muBR,sigma2BR, ...
        muRU,rhoRUhop);

    [muSNR,sigma2Wick,~,Cmat] = evaluate_gamma_metric( ...
        rhoRU,rhoUR,rhoRB,rhoBR, ...
        gamma,W, ...
        [],muFeff,sigma2Feff, ...
        lspBR.mu_XPR,lspBR.sigma_XPR, ...
        lspRU.mu_XPR,lspRU.sigma_XPR, ...
        muBR,sigma2BR, ...
        muRU,sigma2RU,UBR);

    muXPR_BR = double(lspBR.mu_XPR);
    sigmaXPR_BR = double(lspBR.sigma_XPR);
    muXPR_RU = double(lspRU.mu_XPR);
    sigmaXPR_RU = double(lspRU.sigma_XPR);

    sigma2BR = double(sigma2BR);
    sigma2RU = double(sigma2RU);
    muSNR = double(muSNR);
    sigma2Wick = double(sigma2Wick);

    save(outFile, ...
        'rhoRB','rhoBR','rhoRU','rhoUR','rhoRUhop', ...
        'muBR','sigma2BR','muRU','sigma2RU', ...
        'muXPR_BR','sigmaXPR_BR','muXPR_RU','sigmaXPR_RU', ...
        'W','z','phi','beta','gamma', ...
        'UBR','muFeff','sigma2Feff','muSNR','Cmat','sigma2Wick', ...
        '-v7');

    fprintf('\nStage-3 golden case saved:\n  %s\n',string(outFile));
    fprintf('nRIS       : %d\n',nRIS);
    fprintf('nT          : %d\n',nT);
    fprintf('nR          : %d\n',size(muRU,1));
    fprintf('muSNR       : %.16g\n',muSNR);
    fprintf('sigma2Wick  : %.16g\n',sigma2Wick);
end
