function export_rho_parity_case( ...
    outFile,gnb2ris,ris2ue,geometry,c0,lambda0,KBR,KRU,lspBR,lspRU)
%EXPORT_RHO_PARITY_CASE Export current second-order rho engine golden case.
%
% Uses the same functions as the current V3 environment path:
%   compute_ch_eff_rho_avg_fast
%   compute_ch_rho_avg
%
% Example:
%
% export_rho_parity_case( ...
%     "rho_case.mat", ...
%     gnb2ris,ris2ue,geometry,c0,lambda_0, ...
%     K_BR,K_RU,lsp_BR,lsp_RU);

    [muBR,sigma2BR,dbarTBR,dbarRBR] = ...
        generate_channel_moments_no_cdl( ...
            gnb2ris,geometry.ris2gnb,geometry.gnb2ris, ...
            c0,lambda0,KBR,lspBR);

    [muRU,sigma2RU,dbarTRU,dbarRRU] = ...
        generate_channel_moments_no_cdl( ...
            ris2ue,geometry.ue2ris,geometry.ris2ue, ...
            c0,lambda0,KRU,lspRU);

    [rhoRB,rhoBR] = compute_ch_eff_rho_avg_fast( ...
        dbarTBR,dbarRBR,geometry.ris2gnb,geometry.gnb2ris, ...
        lspBR.mu_ASA,lspBR.sigma_ASA, ...
        lspBR.mu_ZSA,lspBR.sigma_ZSA, ...
        lspBR.mu_ASD,lspBR.sigma_ASD, ...
        lspBR.mu_ZSD,lspBR.sigma_ZSD, ...
        lspBR.c_ASA,lspBR.c_ZSA,lspBR.c_ASD,lspBR.c_ZSD, ...
        lspBR.mu_offset_ZOD,lambda0);

    rhoRUhopBase = compute_ch_rho_avg( ...
        dbarTRU,geometry.ris2ue, ...
        lspRU.mu_ASD,lspRU.sigma_ASD, ...
        lspRU.mu_ZSD,lspRU.sigma_ZSD, ...
        lspRU.c_ASD,lspRU.c_ZSD, ...
        lspRU.mu_offset_ZOD,lambda0);

    rhoRUhop = sigma2RU*rhoRUhopBase;

    [rhoRU,rhoUR] = compute_ch_eff_rho_avg_fast( ...
        dbarTRU,dbarRRU,geometry.ue2ris,geometry.ris2ue, ...
        lspRU.mu_ASA,lspRU.sigma_ASA, ...
        lspRU.mu_ZSA,lspRU.sigma_ZSA, ...
        lspRU.mu_ASD,lspRU.sigma_ASD, ...
        lspRU.mu_ZSD,lspRU.sigma_ZSD, ...
        lspRU.c_ASA,lspRU.c_ZSA,lspRU.c_ASD,lspRU.c_ZSD, ...
        lspRU.mu_offset_ZOD,lambda0);

    arrivalBR = double(geometry.ris2gnb(:));
    departureBR = double(geometry.gnb2ris(:));
    arrivalRU = double(geometry.ue2ris(:));
    departureRU = double(geometry.ris2ue(:));

    muASA_BR = double(lspBR.mu_ASA); sigASA_BR = double(lspBR.sigma_ASA);
    muZSA_BR = double(lspBR.mu_ZSA); sigZSA_BR = double(lspBR.sigma_ZSA);
    muASD_BR = double(lspBR.mu_ASD); sigASD_BR = double(lspBR.sigma_ASD);
    muZSD_BR = double(lspBR.mu_ZSD); sigZSD_BR = double(lspBR.sigma_ZSD);
    cASA_BR = double(lspBR.c_ASA); cZSA_BR = double(lspBR.c_ZSA);
    cASD_BR = double(lspBR.c_ASD); cZSD_BR = double(lspBR.c_ZSD);
    muOffsetZOD_BR = double(lspBR.mu_offset_ZOD);

    muASA_RU = double(lspRU.mu_ASA); sigASA_RU = double(lspRU.sigma_ASA);
    muZSA_RU = double(lspRU.mu_ZSA); sigZSA_RU = double(lspRU.sigma_ZSA);
    muASD_RU = double(lspRU.mu_ASD); sigASD_RU = double(lspRU.sigma_ASD);
    muZSD_RU = double(lspRU.mu_ZSD); sigZSD_RU = double(lspRU.sigma_ZSD);
    cASA_RU = double(lspRU.c_ASA); cZSA_RU = double(lspRU.c_ZSA);
    cASD_RU = double(lspRU.c_ASD); cZSD_RU = double(lspRU.c_ZSD);
    muOffsetZOD_RU = double(lspRU.mu_offset_ZOD);

    c0 = double(c0);
    lambda0 = double(lambda0);
    KBR = double(KBR);
    KRU = double(KRU);
    sigma2BR = double(sigma2BR);
    sigma2RU = double(sigma2RU);

    save(outFile, ...
        'c0','lambda0','KBR','KRU', ...
        'dbarTBR','dbarRBR','dbarTRU','dbarRRU', ...
        'muBR','muRU','sigma2BR','sigma2RU', ...
        'arrivalBR','departureBR','arrivalRU','departureRU', ...
        'muASA_BR','sigASA_BR','muZSA_BR','sigZSA_BR', ...
        'muASD_BR','sigASD_BR','muZSD_BR','sigZSD_BR', ...
        'cASA_BR','cZSA_BR','cASD_BR','cZSD_BR','muOffsetZOD_BR', ...
        'muASA_RU','sigASA_RU','muZSA_RU','sigZSA_RU', ...
        'muASD_RU','sigASD_RU','muZSD_RU','sigZSD_RU', ...
        'cASA_RU','cZSA_RU','cASD_RU','cZSD_RU','muOffsetZOD_RU', ...
        'rhoRB','rhoBR','rhoRU','rhoUR','rhoRUhopBase','rhoRUhop', ...
        '-v7');

    fprintf('\nStage-2 rho golden case saved:\n  %s\n',string(outFile));
    fprintf('rhoRB : %s\n',mat2str(size(rhoRB)));
    fprintf('rhoBR : %s\n',mat2str(size(rhoBR)));
    fprintf('rhoRU : %s\n',mat2str(size(rhoRU)));
    fprintf('rhoUR : %s\n',mat2str(size(rhoUR)));
    fprintf('rhoRUhop : %s\n',mat2str(size(rhoRUhop)));
end
